apiVersion: v1
kind: Pod
metadata:
  name: infected-models-keras-2
  namespace: malicious-models
spec:
  containers:
    - name: infected-models-keras-2
      image: europe-west2-docker.pkg.dev/central-registry/conteval/raradwanski/infected-models:keras-2
      command: ["sleep", "infinity"]
  restartPolicy: Never
